name: Deploy to Netlify

on:
  push:
    branches:
      - main
      - staging
      - develop  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      name: development
    if:  github.event.ref == 'refs/heads/main'
    needs: [build]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Dev
      uses: nwtgck/actions-netlify@v3.0
      with:
        args: deploy --development --dir=. 
      
  deploy-staging:
    runs-on: ubuntu-latest
    env:
      name: staging
    if:  github.event.ref == 'refs/heads/main'
    needs: [deploy-dev]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Staging
      uses: nwtgck/actions-netlify@v3.0
      with:
        args: deploy --staging --dir=. --alias=https://prod-setup.netlify.app
      
  deploy-production:
    runs-on: ubuntu-latest
    env:
      name: prod
      url: https://prod-setup.netlify.app
    if: github.event.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Production
      uses: nwtgck/actions-netlify@v3.0
      with:
        args: deploy --prod --dir=.
      
  
