name: Deploy to Netlify

on:
  push:
    branches:
      - main
      - staging
      - develop  

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/staging' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Staging
      uses: nwtgck/actions-netlify@v3.0
      with:
        args: deploy --staging --dir=. --alias="https://prod-setup.netlify.app"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_STAGING_SITE_ID }}

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Production
      uses: nwtgck/actions-netlify@v3.0
      with:
        args: deploy --production --dir=. --alias="https://prod-setup.netlify.app"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  deploy-dev:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Dev
      uses: nwtgck/actions-netlify@v3.0
      with:
        args: deploy --development --dir=. --alias="dev-example-url.netlify.app"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEV_SITE_ID }}
