name: Netlify Deployment

on:
  push:
    branches:
      - main # this line shows that the pipeline would only be triggered if we push to the main branch
      - staging
      - production
jobs:
  build:
    runs-on: ubuntu-latest # our job would be running on ubuntu os
    steps:
      - uses: actions/checkout@v4 # the workflow needs to checkout the current repository
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: development
    env:
       # we expect this job to run in the dev environment
      url:   https://muna-dev.netlify.app           # this url is gotten from netlify and it is specifically for the dev environment
      NNETLIFY_DEVELOP_SITE_ID:   $ {{ secrets.NETLIFY_DEVELOP_SITE_ID }}     # this is the site id for the dev url

    if:  github.event.ref == 'refs/heads/dev' # we want this job to be triggered once we push to the dev branch
    
    steps:
    - name: Deploy to Dev     
      uses: nwtgck/actions-netlify@v3.0
      with:
        args: deploy --development --dir=.    # this line of code is to deploy our website files using the development env and the dir where the files are is root directory
      
  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url:  https://staging-env.netlify.app
    env:
      
      NETLIFY_STAGING_SITE_ID: $ {{ secrets.NETLIFY_STAGING_SITE_ID }}
      
    if:  github.event.ref == 'refs/heads/staging'       #we are assuming we have a staging branch, so this job would be triggered is we push code to the staging branch
                                  

    steps:
    - name: Deploy to Staging
      uses: nwtgck/actions-netlify@v3.0
      with:
        args: deploy --staging --dir=.
      
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url:  https://prod-setup.netlify.app
    env:
      NETLIFY_PROD_SITE_ID: $ {{ secrets.NETLIFY_PROD_SITE_ID }}
    if: github.event.ref == 'refs/heads/main'       # production deployment would be triggered when we push to the main branch
    steps:
    - name: Deploy to Production
      uses: nwtgck/actions-netlify@v3.0
      with:
        args: deploy --prod --dir=.
      
  
