name: Deploy to Netlify

on:
  push:
    branches:
      - main
      - staging # Add your staging branch or any other branch you want to trigger staging deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DEVELOPMENT_SITE_ID: ${{ secrets.NETLIFY_DEVELOPMENT_SITE_ID }}
          NETLIFY_STAGING_SITE_ID: ${{ secrets.NETLIFY_STAGING_SITEID }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Deploying to production"
            netlify deploy --prod --dir=. --site=$NETLIFY_DEVELOPMENT_SITE_ID --auth=$NETLIFY_AUTH_TOKEN
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            echo "Deploying to staging"
            netlify deploy --dir=. --site=$NETLIFY_STAGING_SITEID --auth=$NETLIFY_AUTH_TOKEN
          else
            echo "No deployment action taken for this branch"
          fi
          curl -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" \
               -F "file=@./dist" \ # Update to your actual build output directory
               -F "site_id=$NETLIFY_STAGING_SITEID" \
               -F "path=/" \
               https://api.netlify.com/api/v1/sites/$NETLIFY_STAGING_SITEID/deploys
