name: Deploy to Netlify

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust this to the Node.js version you're using

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Build project
        run: |
          # Run your build command here
          # e.g., npm install && npm run build
          echo "Build your project here"

      - name: Display GitHub Ref
        run: echo "GITHUB_REF=$GITHUB_REF"

      - name: Set Netlify Site ID
        id: set_site_id
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "NETLIFY_SITE_ID=${{ secrets.NETLIFY_DEVELOPMENT_SITE_ID }}" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == 'refs/heads/staging' ]]; then
            echo "NETLIFY_SITE_ID=${{ secrets.NETLIFY_STAGING_SITE_ID }}" >> $GITHUB_ENV
          else
            echo "Branch not recognized. Exiting."
            exit 1
          fi

      - name: Verify Site ID
        run: echo "Deploying to Netlify site ID:" $NETLIFY_SITE_ID

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          # Deploy to Netlify using Netlify CLI
          netlify deploy --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID --dir ./dist --prod # Adjust --dir if necessary
