name: Deploy to Netlify

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          # Run your build command here
          # e.g., npm install && npm run build
          echo "Build your project here"

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DEVELOPMENT_SITE_ID: ${{ secrets.NETLIFY_DEVELOPMENT_SITE_ID }}
          NETLIFY_STAGING_SITE_ID: ${{ secrets.NETLIFY_STAGING_SITE_ID }}
        run: |
          # Set the Netlify site ID based on the branch
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            NETLIFY_SITE_ID=$NETLIFY_DEVELOPMENT_SITE_ID
          elif [[ $GITHUB_REF == 'refs/heads/staging' ]]; then
            NETLIFY_SITE_ID=$NETLIFY_STAGING_SITE_ID
          fi

          # Deploy to Netlify
          curl -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" \
               -F "file=@./" \ # Update to your actual build output directory
               -F "site_id=$NETLIFY_SITE_ID" \
               -F "path=/" \
               https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/deploys
