name: Deploy to Netlify

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ZIP of static files
        run: zip -r site.zip .  # Adjust this command based on where your files are

      - name: Deploy to Netlify
        run: |
          response=$(curl -X POST "https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/deploys" \
                            -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" \
                            -F "file=.")
          echo "Deployment response: $response"
          echo "$response" | jq -r '.deploy_url' > deploy_url.txt
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Output deployment URL
        run: |
          echo "Your website is live at $(cat deploy_url.txt)"
