name: Deploy to Netlify

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          curl -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" \
               -F "file=@./" \
               -F "site_id=$NETLIFY_DEVELOPMENT_SITE_ID" \
               -F "path=/" \
               https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/deploys
