name: Deploy to Netlify

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Build project
        run: |
          # Run your build command here
          # e.g., npm install && npm run build
          echo "Build your project here"

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          # Set the Netlify site ID based on the branch
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            NETLIFY_SITE_ID=$NETLIFY_DEVELOPMENT_SITE_ID
          elif [[ $GITHUB_REF == 'refs/heads/staging' ]]; then
            NETLIFY_SITE_ID=$NETLIFY_STAGING_SITE_ID
          else
            echo "Branch not recognized. Exiting."
            exit 1
          fi

          # Deploy to Netlify using Netlify CLI
          netlify deploy --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir .
